Tests run  1
Errors  [(<CodeGenSuite.CheckCodeGenSuite testMethod=test_case_99>, 'Traceback (most recent call last):\n  File "test/CodeGenSuite.py", line 2161, in test_case_99\n    self.assertTrue(TestCodeGen.test(input, expect, 598))\n  File "test/TestUtils.py", line 163, in test\n    codeGen.gen(asttree, path)\n  File "./main/bkit/codegen/CodeGenerator.py", line 987, in gen\n    gc = CodeGenVisitor(ast, gl, dir_)\n  File "./main/bkit/codegen/CodeGenerator.py", line 1004, in __init__\n    self.symbols_table = list(filter(lambda x: type(x.mtype) is MType and x.name not in builtin_fns, self.static_check.check()[0]))\n  File "./main/bkit/codegen/CodeGenerator.py", line 217, in check\n    return self.visit(self.ast,self.global_envi)\n  File "./main/bkit/utils/Visitor.py", line 7, in visit\n    return ast.accept(self,param)\n  File "./main/bkit/utils/AST.py", line 55, in accept\n    return v.visitProgram(self, param)\n  File "./main/bkit/codegen/CodeGenerator.py", line 239, in visitProgram\n    raise UnreachableFunction(fn_name)\nCodeGenerator.UnreachableFunction: str(UnreachableFunction(\'goo\'))\n')]
[]
Test output
 E
======================================================================
ERROR: test_case_99 (CodeGenSuite.CheckCodeGenSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/CodeGenSuite.py", line 2161, in test_case_99
    self.assertTrue(TestCodeGen.test(input, expect, 598))
  File "test/TestUtils.py", line 163, in test
    codeGen.gen(asttree, path)
  File "./main/bkit/codegen/CodeGenerator.py", line 987, in gen
    gc = CodeGenVisitor(ast, gl, dir_)
  File "./main/bkit/codegen/CodeGenerator.py", line 1004, in __init__
    self.symbols_table = list(filter(lambda x: type(x.mtype) is MType and x.name not in builtin_fns, self.static_check.check()[0]))
  File "./main/bkit/codegen/CodeGenerator.py", line 217, in check
    return self.visit(self.ast,self.global_envi)
  File "./main/bkit/utils/Visitor.py", line 7, in visit
    return ast.accept(self,param)
  File "./main/bkit/utils/AST.py", line 55, in accept
    return v.visitProgram(self, param)
  File "./main/bkit/codegen/CodeGenerator.py", line 239, in visitProgram
    raise UnreachableFunction(fn_name)
CodeGenerator.UnreachableFunction: str(UnreachableFunction('goo'))

----------------------------------------------------------------------
Ran 1 test in 0.062s

FAILED (errors=1)

